# Generated by Django 5.2.8 on 2025-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/photo", verbose_name="Превью"
            ),
        ),
    ]
