# Generated by Django 5.2.8 on 2025-12-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(verbose_name="Статья"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
